python -W ignore step5_calculateMetrics.py --pred_path BDMAP_O_intratomo_50
python -W ignore step5_calculateMetrics.py --pred_path BDMAP_O_nerf_50
python -W ignore step5_calculateMetrics.py --pred_path BDMAP_O_tensorf_50
python -W ignore step5_calculateMetrics.py --pred_path BDMAP_O_r2_gaussian_50
python -W ignore step5_calculateMetrics.py --pred_path BDMAP_O_naf_50
python -W ignore step5_calculateMetrics.py --pred_path BDMAP_O_FDK_50
python -W ignore step5_calculateMetrics.py --pred_path BDMAP_O_SART_50
python -W ignore step5_calculateMetrics.py --pred_path BDMAP_O_ASD_POCS_50
python -W ignore step5_calculateMetrics.py --pred_path BDMAP_O_Lineformer_50